spring:
  application:
    name: Primeiros Passos SpringBoot
  datasource:
    url: jdbc:h2:mem:primeiro-passos-springboot
    username: sa
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console